version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "webhook-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q26kcfv0s3z8"
s3_prefix = "webhook-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "MyWebhookURL=\"https://webhook.site/c52ad2e2-b5ed-4315-bbeb-6e9f17f9097b\""
image_repositories = []
