version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "eventbridge-destination-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q26kcfv0s3z8"
s3_prefix = "eventbridge-destination-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "MyApiWithPathURL=\"https://api.zippopotam.us/us/*\""
image_repositories = []
